export interface WordBookEntry {
  word: string
  pinyin: string
  meaning: string
  tips?: string
}

export interface WordBook {
  id: number
  name: string
  emoji: string
  color: string
  description: string
  words: WordBookEntry[]
}

export const WORD_BOOKS: WordBook[] = [
  {
    id: 1,
    name: 'Sprout',
    emoji: '🌱',
    color: '#FF6B6B',
    description: 'Basic words for beginners — greetings, numbers, colors, family',
    words: [
      // Greetings
      { word: '你好', pinyin: 'nǐ hǎo', meaning: 'hello', tips: '你 = you, 好 = good → "you good" = hello 👋' },
      { word: '再见', pinyin: 'zàijiàn', meaning: 'goodbye' },
      { word: '谢谢', pinyin: 'xièxie', meaning: 'thank you' },
      { word: '不客气', pinyin: 'bú kèqì', meaning: "you're welcome" },
      { word: '对不起', pinyin: 'duìbuqǐ', meaning: 'sorry' },
      { word: '没关系', pinyin: 'méiguānxì', meaning: "it's okay, no problem" },
      { word: '请', pinyin: 'qǐng', meaning: 'please' },
      { word: '早上好', pinyin: 'zǎoshang hǎo', meaning: 'good morning' },
      { word: '晚安', pinyin: `wǎn'ān`, meaning: 'good night' },
      // Self & Family
      { word: '我', pinyin: 'wǒ', meaning: 'I, me' },
      { word: '你', pinyin: 'nǐ', meaning: 'you' },
      { word: '他', pinyin: 'tā', meaning: 'he, him' },
      { word: '她', pinyin: 'tā', meaning: 'she, her' },
      { word: '我们', pinyin: 'wǒmen', meaning: 'we, us' },
      { word: '名字', pinyin: 'míngzì', meaning: 'name' },
      { word: '叫', pinyin: 'jiào', meaning: 'to be called' },
      { word: '岁', pinyin: 'suì', meaning: 'years old' },
      { word: '家', pinyin: 'jiā', meaning: 'family, home' },
      { word: '爸爸', pinyin: 'bàba', meaning: 'dad' },
      { word: '妈妈', pinyin: 'māma', meaning: 'mom' },
      { word: '哥哥', pinyin: 'gēge', meaning: 'older brother' },
      { word: '姐姐', pinyin: 'jiějie', meaning: 'older sister' },
      { word: '弟弟', pinyin: 'dìdi', meaning: 'younger brother' },
      { word: '妹妹', pinyin: 'mèimei', meaning: 'younger sister' },
      { word: '有', pinyin: 'yǒu', meaning: 'to have' },
      { word: '爱', pinyin: 'ài', meaning: 'to love' },
      { word: '朋友', pinyin: 'péngyǒu', meaning: 'friend' },
      // Numbers & Quantities
      { word: '一', pinyin: 'yī', meaning: 'one' },
      { word: '二', pinyin: 'èr', meaning: 'two' },
      { word: '三', pinyin: 'sān', meaning: 'three' },
      { word: '四', pinyin: 'sì', meaning: 'four' },
      { word: '五', pinyin: 'wǔ', meaning: 'five' },
      { word: '六', pinyin: 'liù', meaning: 'six' },
      { word: '七', pinyin: 'qī', meaning: 'seven' },
      { word: '八', pinyin: 'bā', meaning: 'eight' },
      { word: '九', pinyin: 'jiǔ', meaning: 'nine' },
      { word: '十', pinyin: 'shí', meaning: 'ten' },
      { word: '个', pinyin: 'gè', meaning: 'general measure word' },
      // Colors & Descriptions
      { word: '红色', pinyin: 'hóngsè', meaning: 'red' },
      { word: '蓝色', pinyin: 'lánsè', meaning: 'blue' },
      { word: '绿色', pinyin: 'lǜsè', meaning: 'green' },
      { word: '黄色', pinyin: 'huángsè', meaning: 'yellow' },
      { word: '白色', pinyin: 'báisè', meaning: 'white' },
      { word: '黑色', pinyin: 'hēisè', meaning: 'black' },
      { word: '大', pinyin: 'dà', meaning: 'big' },
      { word: '小', pinyin: 'xiǎo', meaning: 'small' },
      { word: '高', pinyin: 'gāo', meaning: 'tall' },
      { word: '漂亮', pinyin: 'piàoliang', meaning: 'pretty' },
      // Food
      { word: '吃', pinyin: 'chī', meaning: 'to eat' },
      { word: '喝', pinyin: 'hē', meaning: 'to drink' },
      { word: '水', pinyin: 'shuǐ', meaning: 'water' },
      { word: '苹果', pinyin: 'píngguǒ', meaning: 'apple' },
      { word: '米饭', pinyin: 'mǐfàn', meaning: 'rice (cooked)' },
      { word: '牛奶', pinyin: 'niúnǎi', meaning: 'milk' },
      // Animals
      { word: '猫', pinyin: 'māo', meaning: 'cat' },
      { word: '狗', pinyin: 'gǒu', meaning: 'dog' },
      { word: '鱼', pinyin: 'yú', meaning: 'fish' },
      { word: '鸟', pinyin: 'niǎo', meaning: 'bird' },
      // Actions & Body
      { word: '看', pinyin: 'kàn', meaning: 'to look, to see' },
      { word: '听', pinyin: 'tīng', meaning: 'to listen' },
      { word: '说', pinyin: 'shuō', meaning: 'to speak' },
      { word: '走', pinyin: 'zǒu', meaning: 'to walk' },
      { word: '跑', pinyin: 'pǎo', meaning: 'to run' },
      { word: '坐', pinyin: 'zuò', meaning: 'to sit' },
      { word: '站', pinyin: 'zhàn', meaning: 'to stand' },
      { word: '手', pinyin: 'shǒu', meaning: 'hand' },
      { word: '眼睛', pinyin: 'yǎnjīng', meaning: 'eyes' },
      { word: '头', pinyin: 'tóu', meaning: 'head' },
      // Nature
      { word: '花', pinyin: 'huā', meaning: 'flower' },
      { word: '树', pinyin: 'shù', meaning: 'tree' },
      { word: '太阳', pinyin: 'tàiyang', meaning: 'sun' },
      { word: '月亮', pinyin: 'yuèliang', meaning: 'moon' },
      { word: '星星', pinyin: 'xīngxing', meaning: 'star' },
    ],
  },
  {
    id: 2,
    name: 'Seedling',
    emoji: '🌿',
    color: '#4ECDC4',
    description: 'Daily life vocabulary — school, home, weather, emotions, routines',
    words: [
      // School
      { word: '学校', pinyin: 'xuéxiào', meaning: 'school' },
      { word: '老师', pinyin: 'lǎoshī', meaning: 'teacher' },
      { word: '同学', pinyin: 'tóngxué', meaning: 'classmate' },
      { word: '学习', pinyin: 'xuéxí', meaning: 'to study' },
      { word: '读书', pinyin: 'dúshū', meaning: 'to read (a book)' },
      { word: '写字', pinyin: 'xiě zì', meaning: 'to write characters' },
      { word: '画画', pinyin: 'huàhuà', meaning: 'to draw' },
      { word: '唱歌', pinyin: 'chànggē', meaning: 'to sing' },
      { word: '跳舞', pinyin: 'tiàowǔ', meaning: 'to dance' },
      { word: '数学', pinyin: 'shùxué', meaning: 'math' },
      { word: '中文', pinyin: 'zhōngwén', meaning: 'Chinese language' },
      { word: '英文', pinyin: 'yīngwén', meaning: 'English language' },
      { word: '书', pinyin: 'shū', meaning: 'book' },
      { word: '作业', pinyin: 'zuòyè', meaning: 'homework' },
      // Daily Routines
      { word: '每天', pinyin: 'měitiān', meaning: 'every day' },
      { word: '今天', pinyin: 'jīntiān', meaning: 'today' },
      { word: '明天', pinyin: 'míngtiān', meaning: 'tomorrow' },
      { word: '昨天', pinyin: 'zuótiān', meaning: 'yesterday' },
      { word: '早上', pinyin: 'zǎoshang', meaning: 'morning' },
      { word: '中午', pinyin: 'zhōngwǔ', meaning: 'noon' },
      { word: '晚上', pinyin: 'wǎnshang', meaning: 'evening' },
      { word: '起床', pinyin: 'qǐchuáng', meaning: 'to get up' },
      { word: '洗脸', pinyin: 'xǐ liǎn', meaning: 'to wash face' },
      { word: '刷牙', pinyin: 'shuā yá', meaning: 'to brush teeth' },
      { word: '穿', pinyin: 'chuān', meaning: 'to wear, to put on' },
      { word: '衣服', pinyin: 'yīfu', meaning: 'clothes' },
      { word: '早饭', pinyin: 'zǎofàn', meaning: 'breakfast' },
      { word: '午饭', pinyin: 'wǔfàn', meaning: 'lunch' },
      { word: '晚饭', pinyin: 'wǎnfàn', meaning: 'dinner' },
      { word: '上学', pinyin: 'shàngxué', meaning: 'to go to school' },
      { word: '放学', pinyin: 'fàngxué', meaning: 'school ends, to leave school' },
      { word: '回家', pinyin: 'huíjiā', meaning: 'to go home' },
      { word: '睡觉', pinyin: 'shuìjiào', meaning: 'to sleep' },
      // Weather & Seasons
      { word: '天气', pinyin: 'tiānqì', meaning: 'weather' },
      { word: '晴天', pinyin: 'qíngtiān', meaning: 'sunny day' },
      { word: '下雨', pinyin: 'xiàyǔ', meaning: 'to rain' },
      { word: '下雪', pinyin: 'xiàxuě', meaning: 'to snow' },
      { word: '风', pinyin: 'fēng', meaning: 'wind' },
      { word: '云', pinyin: 'yún', meaning: 'cloud' },
      { word: '春天', pinyin: 'chūntiān', meaning: 'spring' },
      { word: '夏天', pinyin: 'xiàtiān', meaning: 'summer' },
      { word: '秋天', pinyin: 'qiūtiān', meaning: 'autumn' },
      { word: '冬天', pinyin: 'dōngtiān', meaning: 'winter' },
      // Emotions
      { word: '开心', pinyin: 'kāixīn', meaning: 'happy' },
      { word: '难过', pinyin: 'nánguò', meaning: 'sad' },
      { word: '生气', pinyin: 'shēngqì', meaning: 'angry' },
      { word: '害怕', pinyin: 'hàipà', meaning: 'scared' },
      { word: '喜欢', pinyin: 'xǐhuān', meaning: 'to like' },
      { word: '想', pinyin: 'xiǎng', meaning: 'to think, to miss, would like' },
      // Actions & Movement
      { word: '来', pinyin: 'lái', meaning: 'to come' },
      { word: '去', pinyin: 'qù', meaning: 'to go' },
      { word: '进', pinyin: 'jìn', meaning: 'to enter' },
      { word: '出', pinyin: 'chū', meaning: 'to go out' },
      { word: '上', pinyin: 'shàng', meaning: 'up, to go up' },
      { word: '下', pinyin: 'xià', meaning: 'down, to go down' },
      { word: '玩', pinyin: 'wán', meaning: 'to play' },
      { word: '买', pinyin: 'mǎi', meaning: 'to buy' },
      { word: '卖', pinyin: 'mài', meaning: 'to sell' },
      // Home & Places
      { word: '房间', pinyin: 'fángjiān', meaning: 'room' },
      { word: '门', pinyin: 'mén', meaning: 'door' },
      { word: '窗', pinyin: 'chuāng', meaning: 'window' },
      { word: '桌子', pinyin: 'zhuōzi', meaning: 'table' },
      { word: '椅子', pinyin: 'yǐzi', meaning: 'chair' },
      { word: '床', pinyin: 'chuáng', meaning: 'bed' },
      { word: '公园', pinyin: 'gōngyuán', meaning: 'park' },
      { word: '商店', pinyin: 'shāngdiàn', meaning: 'store, shop' },
      // Food & Drink
      { word: '面包', pinyin: 'miànbāo', meaning: 'bread' },
      { word: '鸡蛋', pinyin: 'jīdàn', meaning: 'egg' },
      { word: '肉', pinyin: 'ròu', meaning: 'meat' },
      { word: '蔬菜', pinyin: 'shūcài', meaning: 'vegetable' },
      { word: '水果', pinyin: 'shuǐguǒ', meaning: 'fruit' },
      { word: '蛋糕', pinyin: 'dàngāo', meaning: 'cake' },
      { word: '糖', pinyin: 'táng', meaning: 'candy, sugar' },
      // Body & Health
      { word: '嘴巴', pinyin: 'zuǐba', meaning: 'mouth' },
      { word: '鼻子', pinyin: 'bízi', meaning: 'nose' },
      { word: '耳朵', pinyin: 'ěrduo', meaning: 'ear' },
      { word: '头发', pinyin: 'tóufa', meaning: 'hair' },
      { word: '脚', pinyin: 'jiǎo', meaning: 'foot' },
      // Transport
      { word: '车', pinyin: 'chē', meaning: 'vehicle, car' },
      { word: '公共汽车', pinyin: 'gōnggòng qìchē', meaning: 'bus' },
      { word: '自行车', pinyin: 'zìxíngchē', meaning: 'bicycle' },
      { word: '飞机', pinyin: 'fēijī', meaning: 'airplane' },
      // Descriptions
      { word: '好', pinyin: 'hǎo', meaning: 'good' },
      { word: '坏', pinyin: 'huài', meaning: 'bad' },
      { word: '快', pinyin: 'kuài', meaning: 'fast' },
      { word: '慢', pinyin: 'màn', meaning: 'slow' },
      { word: '新', pinyin: 'xīn', meaning: 'new' },
      { word: '旧', pinyin: 'jiù', meaning: 'old (things)' },
      { word: '多', pinyin: 'duō', meaning: 'many, much' },
      { word: '少', pinyin: 'shǎo', meaning: 'few, little' },
      // Pronouns & Question words
      { word: '什么', pinyin: 'shénme', meaning: 'what' },
      { word: '谁', pinyin: 'shuí', meaning: 'who' },
      { word: '哪儿', pinyin: 'nǎr', meaning: 'where' },
      { word: '为什么', pinyin: 'wèishénme', meaning: 'why' },
      { word: '怎么', pinyin: 'zěnme', meaning: 'how' },
      { word: '几', pinyin: 'jǐ', meaning: 'how many (small numbers)' },
      // Animals
      { word: '兔子', pinyin: 'tùzi', meaning: 'rabbit' },
      { word: '猴子', pinyin: 'hóuzi', meaning: 'monkey' },
      { word: '熊猫', pinyin: 'xióngmāo', meaning: 'panda' },
      { word: '大象', pinyin: 'dàxiàng', meaning: 'elephant' },
      { word: '老虎', pinyin: 'lǎohǔ', meaning: 'tiger' },
    ],
  },
  {
    id: 3,
    name: 'Sapling',
    emoji: '🌳',
    color: '#45B7D1',
    description: 'Intermediate vocabulary — society, culture, nature, storytelling',
    words: [
      // Time & Frequency
      { word: '时候', pinyin: 'shíhou', meaning: 'time (when), moment' },
      { word: '现在', pinyin: 'xiànzài', meaning: 'now' },
      { word: '以前', pinyin: 'yǐqián', meaning: 'before, in the past' },
      { word: '以后', pinyin: 'yǐhòu', meaning: 'after, in the future' },
      { word: '常常', pinyin: 'chángcháng', meaning: 'often' },
      { word: '有时候', pinyin: 'yǒushíhou', meaning: 'sometimes' },
      { word: '分钟', pinyin: 'fēnzhōng', meaning: 'minute' },
      { word: '小时', pinyin: 'xiǎoshí', meaning: 'hour' },
      // Nature & Geography
      { word: '山', pinyin: 'shān', meaning: 'mountain' },
      { word: '河', pinyin: 'hé', meaning: 'river' },
      { word: '海', pinyin: 'hǎi', meaning: 'sea, ocean' },
      { word: '森林', pinyin: 'sēnlín', meaning: 'forest' },
      { word: '草原', pinyin: 'cǎoyuán', meaning: 'grassland' },
      { word: '沙漠', pinyin: 'shāmò', meaning: 'desert' },
      { word: '大自然', pinyin: 'dàzìrán', meaning: 'nature' },
      // China & Culture
      { word: '中国', pinyin: 'zhōngguó', meaning: 'China' },
      { word: '春节', pinyin: 'chūnjié', meaning: 'Spring Festival (Chinese New Year)' },
      { word: '节日', pinyin: 'jiérì', meaning: 'festival, holiday' },
      { word: '红包', pinyin: 'hóngbāo', meaning: 'red envelope' },
      { word: '饺子', pinyin: 'jiǎozi', meaning: 'dumplings' },
      { word: '年糕', pinyin: 'niángāo', meaning: 'New Year rice cake' },
      { word: '灯笼', pinyin: 'dēnglóng', meaning: 'lantern' },
      { word: '生日', pinyin: 'shēngrì', meaning: 'birthday' },
      { word: '礼物', pinyin: 'lǐwù', meaning: 'gift, present' },
      // Places & Community
      { word: '城市', pinyin: 'chéngshì', meaning: 'city' },
      { word: '农村', pinyin: 'nóngcūn', meaning: 'countryside, village' },
      { word: '图书馆', pinyin: 'túshūguǎn', meaning: 'library' },
      { word: '博物馆', pinyin: 'bówùguǎn', meaning: 'museum' },
      { word: '医院', pinyin: 'yīyuàn', meaning: 'hospital' },
      { word: '银行', pinyin: 'yínháng', meaning: 'bank' },
      { word: '饭店', pinyin: 'fàndiàn', meaning: 'restaurant' },
      { word: '机场', pinyin: 'jīchǎng', meaning: 'airport' },
      // Occupations
      { word: '医生', pinyin: 'yīshēng', meaning: 'doctor' },
      { word: '护士', pinyin: 'hùshi', meaning: 'nurse' },
      { word: '警察', pinyin: 'jǐngchá', meaning: 'police officer' },
      { word: '司机', pinyin: 'sījī', meaning: 'driver' },
      { word: '厨师', pinyin: 'chúshī', meaning: 'chef' },
      { word: '农民', pinyin: 'nóngmín', meaning: 'farmer' },
      // Language & Communication
      { word: '故事', pinyin: 'gùshi', meaning: 'story' },
      { word: '问题', pinyin: 'wèntí', meaning: 'question, problem' },
      { word: '答案', pinyin: `dá'àn`, meaning: 'answer' },
      { word: '意思', pinyin: 'yìsi', meaning: 'meaning' },
      { word: '知道', pinyin: 'zhīdào', meaning: 'to know' },
      { word: '觉得', pinyin: 'juéde', meaning: 'to think, to feel' },
      { word: '告诉', pinyin: 'gàosu', meaning: 'to tell' },
      { word: '问', pinyin: 'wèn', meaning: 'to ask' },
      { word: '回答', pinyin: 'huídá', meaning: 'to answer' },
      // Feelings & Thoughts
      { word: '快乐', pinyin: 'kuàilè', meaning: 'joyful, happy' },
      { word: '感动', pinyin: 'gǎndòng', meaning: 'to be moved, touched' },
      { word: '着急', pinyin: 'zháojí', meaning: 'anxious, worried' },
      { word: '奇怪', pinyin: 'qíguài', meaning: 'strange, weird' },
      { word: '勇敢', pinyin: 'yǒnggǎn', meaning: 'brave' },
      { word: '聪明', pinyin: 'cōngming', meaning: 'smart, clever' },
      // Travel & Movement
      { word: '旅行', pinyin: 'lǚxíng', meaning: 'to travel' },
      { word: '长城', pinyin: 'Chángchéng', meaning: 'the Great Wall' },
      { word: '到达', pinyin: 'dàodá', meaning: 'to arrive' },
      { word: '离开', pinyin: 'líkāi', meaning: 'to leave' },
      { word: '出发', pinyin: 'chūfā', meaning: 'to set off, to depart' },
      // History & Buildings
      { word: '历史', pinyin: 'lìshǐ', meaning: 'history' },
      { word: '古代', pinyin: 'gǔdài', meaning: 'ancient times' },
      { word: '现代', pinyin: 'xiàndài', meaning: 'modern times' },
      { word: '世界', pinyin: 'shìjiè', meaning: 'world' },
      { word: '国家', pinyin: 'guójiā', meaning: 'country, nation' },
      { word: '建筑', pinyin: 'jiànzhù', meaning: 'building, architecture' },
      { word: '桥', pinyin: 'qiáo', meaning: 'bridge' },
      { word: '塔', pinyin: 'tǎ', meaning: 'tower, pagoda' },
      // Descriptions (advanced)
      { word: '美丽', pinyin: 'měilì', meaning: 'beautiful' },
      { word: '特别', pinyin: 'tèbié', meaning: 'special, particularly' },
      { word: '非常', pinyin: 'fēicháng', meaning: 'very, extremely' },
      { word: '最', pinyin: 'zuì', meaning: 'most, -est' },
      { word: '一样', pinyin: 'yíyàng', meaning: 'same, alike' },
      { word: '干净', pinyin: 'gānjìng', meaning: 'clean' },
      { word: '脏', pinyin: 'zāng', meaning: 'dirty' },
      // Actions (advanced)
      { word: '打扫', pinyin: 'dǎsǎo', meaning: 'to clean' },
      { word: '整理', pinyin: 'zhěnglǐ', meaning: 'to organize, to tidy up' },
      { word: '准备', pinyin: 'zhǔnbèi', meaning: 'to prepare' },
      { word: '检查', pinyin: 'jiǎnchá', meaning: 'to check, to inspect' },
      { word: '忘记', pinyin: 'wàngjì', meaning: 'to forget' },
      { word: '记得', pinyin: 'jìde', meaning: 'to remember' },
      { word: '决定', pinyin: 'juédìng', meaning: 'to decide' },
      { word: '帮助', pinyin: 'bāngzhù', meaning: 'to help' },
      // Hobbies & Sports
      { word: '运动', pinyin: 'yùndòng', meaning: 'sports, exercise' },
      { word: '游泳', pinyin: 'yóuyǒng', meaning: 'to swim' },
      { word: '跑步', pinyin: 'pǎobù', meaning: 'to jog, to run' },
      { word: '踢足球', pinyin: 'tī zúqiú', meaning: 'to play soccer' },
      { word: '打篮球', pinyin: 'dǎ lánqiú', meaning: 'to play basketball' },
      { word: '音乐', pinyin: 'yīnyuè', meaning: 'music' },
      // Festivals & Traditions
      { word: '中秋节', pinyin: 'zhōngqiū jié', meaning: 'Mid-Autumn Festival' },
      { word: '月饼', pinyin: 'yuèbǐng', meaning: 'mooncake' },
      { word: '端午节', pinyin: 'duānwǔ jié', meaning: 'Dragon Boat Festival' },
      { word: '粽子', pinyin: 'zòngzi', meaning: 'zongzi (sticky rice dumpling)' },
      // Animals
      { word: '蝴蝶', pinyin: 'húdié', meaning: 'butterfly' },
      { word: '蜜蜂', pinyin: 'mìfēng', meaning: 'honeybee' },
      { word: '天鹅', pinyin: `tiān'é`, meaning: 'swan' },
      { word: '孔雀', pinyin: 'kǒngquè', meaning: 'peacock' },
      { word: '海豚', pinyin: 'hǎitún', meaning: 'dolphin' },
      // Nature
      { word: '彩虹', pinyin: 'cǎihóng', meaning: 'rainbow' },
      { word: '闪电', pinyin: 'shǎndiàn', meaning: 'lightning' },
      { word: '雪', pinyin: 'xuě', meaning: 'snow' },
      { word: '冰', pinyin: 'bīng', meaning: 'ice' },
      // Abstract
      { word: '事情', pinyin: 'shìqing', meaning: 'thing, matter, affair' },
      { word: '机会', pinyin: 'jīhuì', meaning: 'opportunity, chance' },
      { word: '办法', pinyin: 'bànfǎ', meaning: 'method, way' },
      { word: '原因', pinyin: 'yuányīn', meaning: 'reason, cause' },
      { word: '结果', pinyin: 'jiéguǒ', meaning: 'result, outcome' },
      // Connectors
      { word: '因为', pinyin: 'yīnwèi', meaning: 'because' },
      { word: '所以', pinyin: 'suǒyǐ', meaning: 'so, therefore' },
      { word: '但是', pinyin: 'dànshì', meaning: 'but, however' },
      { word: '而且', pinyin: 'érqiě', meaning: 'and, moreover' },
      { word: '或者', pinyin: 'huòzhě', meaning: 'or, either' },
    ],
  },
  {
    id: 4,
    name: 'Tree',
    emoji: '🌲',
    color: '#96CEB4',
    description: 'Advanced vocabulary — idioms, history, abstract concepts, literature',
    words: [
      // Idioms (成语)
      { word: '一心一意', pinyin: 'yīxīn-yīyì', meaning: 'wholeheartedly, with complete dedication', tips: '一(one) + 心(heart) + 一(one) + 意(mind) → one heart, one mind' },
      { word: '三心二意', pinyin: 'sānxīn-èryì', meaning: 'indecisive, half-hearted', tips: '三(three) + 心(heart) + 二(two) + 意(mind) → three hearts, two minds' },
      { word: '五颜六色', pinyin: 'wǔyán-liùsè', meaning: 'colorful, all colors' },
      { word: '千辛万苦', pinyin: 'qiānxīn-wànkǔ', meaning: 'innumerable hardships' },
      { word: '画龙点睛', pinyin: 'huàlóng-diǎnjīng', meaning: 'to add the finishing touch', tips: '画(draw) + 龙(dragon) + 点(dot) + 睛(eye) → dotting the eyes on a painted dragon' },
      { word: '井底之蛙', pinyin: 'jǐngdǐ zhī wā', meaning: 'a person with a very limited outlook', tips: '井(well) + 底(bottom) + 之(\'s) + 蛙(frog) → a frog at the bottom of a well' },
      { word: '亡羊补牢', pinyin: 'wángyáng-bǔláo', meaning: 'better late than never', tips: '亡(lose) + 羊(sheep) + 补(mend) + 牢(pen) → mend the pen after losing the sheep' },
      { word: '守株待兔', pinyin: 'shǒuzhū-dàitù', meaning: 'to wait idly for luck to strike', tips: '守(guard) + 株(tree stump) + 待(wait) + 兔(rabbit) → guard the stump waiting for rabbits' },
      { word: '刻舟求剑', pinyin: 'kèzhōu-qiújiàn', meaning: 'to be rigid and unadaptive', tips: '刻(carve) + 舟(boat) + 求(seek) + 剑(sword) → carving the boat to find a lost sword' },
      { word: '狐假虎威', pinyin: 'hújiǎ-hǔwēi', meaning: 'to bully people by using another\'s power', tips: '狐(fox) + 假(borrow) + 虎(tiger) + 威(power) → the fox borrows the tiger\'s might' },
      // History & Legends
      { word: '皇帝', pinyin: 'huángdì', meaning: 'emperor' },
      { word: '国王', pinyin: 'guówáng', meaning: 'king' },
      { word: '英雄', pinyin: 'yīngxióng', meaning: 'hero' },
      { word: '传说', pinyin: 'chuánshuō', meaning: 'legend, folklore' },
      { word: '神话', pinyin: 'shénhuà', meaning: 'myth, mythology' },
      { word: '龙', pinyin: 'lóng', meaning: 'dragon' },
      { word: '凤凰', pinyin: 'fènghuáng', meaning: 'phoenix' },
      // Science & Technology
      { word: '科学', pinyin: 'kēxué', meaning: 'science' },
      { word: '发明', pinyin: 'fāmíng', meaning: 'to invent, invention' },
      { word: '发现', pinyin: 'fāxiàn', meaning: 'to discover, discovery' },
      { word: '电脑', pinyin: 'diànnǎo', meaning: 'computer' },
      { word: '手机', pinyin: 'shǒujī', meaning: 'mobile phone' },
      { word: '网络', pinyin: 'wǎngluò', meaning: 'internet, network' },
      { word: '信息', pinyin: 'xìnxī', meaning: 'information' },
      { word: '知识', pinyin: 'zhīshi', meaning: 'knowledge' },
      // Environment
      { word: '环境', pinyin: 'huánjìng', meaning: 'environment' },
      { word: '空气', pinyin: 'kōngqì', meaning: 'air' },
      { word: '垃圾', pinyin: 'lājī', meaning: 'garbage, trash' },
      { word: '保护', pinyin: 'bǎohù', meaning: 'to protect' },
      { word: '能源', pinyin: 'néngyuán', meaning: 'energy' },
      { word: '地球', pinyin: 'dìqiú', meaning: 'Earth' },
      // Economy & Society
      { word: '经济', pinyin: 'jīngjì', meaning: 'economy, economics' },
      { word: '文化', pinyin: 'wénhuà', meaning: 'culture' },
      { word: '社会', pinyin: 'shèhuì', meaning: 'society' },
      { word: '传统', pinyin: 'chuántǒng', meaning: 'tradition, traditional' },
      { word: '教育', pinyin: 'jiàoyù', meaning: 'education' },
      // Abstract Concepts
      { word: '幸福', pinyin: 'xìngfú', meaning: 'happiness, well-being' },
      { word: '自由', pinyin: 'zìyóu', meaning: 'freedom, liberty' },
      { word: '和平', pinyin: 'hépíng', meaning: 'peace' },
      { word: '勇气', pinyin: 'yǒngqì', meaning: 'courage' },
      { word: '信任', pinyin: 'xìnrèn', meaning: 'trust' },
      { word: '责任', pinyin: 'zérèn', meaning: 'responsibility' },
      { word: '努力', pinyin: 'nǔlì', meaning: 'effort, to strive' },
      { word: '成功', pinyin: 'chénggōng', meaning: 'success, to succeed' },
      { word: '失败', pinyin: 'shībài', meaning: 'failure, to fail' },
      { word: '经验', pinyin: 'jīngyàn', meaning: 'experience' },
      // Emotions & Relationships
      { word: '感情', pinyin: 'gǎnqíng', meaning: 'emotion, feeling' },
      { word: '友谊', pinyin: 'yǒuyì', meaning: 'friendship' },
      { word: '尊敬', pinyin: 'zūnjìng', meaning: 'to respect' },
      { word: '感谢', pinyin: 'gǎnxiè', meaning: 'to thank, to be grateful' },
      { word: '原谅', pinyin: 'yuánliàng', meaning: 'to forgive' },
      { word: '羡慕', pinyin: 'xiànmù', meaning: 'to envy, to admire' },
      { word: '骄傲', pinyin: `jiāo'ào`, meaning: 'proud, pride' },
      // Literature & Arts
      { word: '诗歌', pinyin: 'shīgē', meaning: 'poetry' },
      { word: '小说', pinyin: 'xiǎoshuō', meaning: 'novel, fiction' },
      { word: '文章', pinyin: 'wénzhāng', meaning: 'article, essay' },
      { word: '作者', pinyin: 'zuòzhě', meaning: 'author' },
      { word: '读者', pinyin: 'dúzhě', meaning: 'reader' },
      { word: '书法', pinyin: 'shūfǎ', meaning: 'calligraphy' },
      { word: '传统节日', pinyin: 'chuántǒng jiérì', meaning: 'traditional festival' },
      // Nature & Universe
      { word: '宇宙', pinyin: 'yǔzhòu', meaning: 'universe, cosmos' },
      { word: '银河', pinyin: 'yínhé', meaning: 'Milky Way' },
      { word: '行星', pinyin: 'xíngxīng', meaning: 'planet' },
      { word: '地球', pinyin: 'dìqiú', meaning: 'Earth' },
      { word: '卫星', pinyin: 'wèixīng', meaning: 'satellite' },
      // Health & Body
      { word: '健康', pinyin: 'jiànkāng', meaning: 'health, healthy' },
      { word: '运动', pinyin: 'yùndòng', meaning: 'exercise, sports' },
      { word: '锻炼', pinyin: 'duànliàn', meaning: 'to exercise, to work out' },
      { word: '休息', pinyin: 'xiūxi', meaning: 'to rest' },
      { word: '生病', pinyin: 'shēngbìng', meaning: 'to get sick' },
      // Time & Age
      { word: '年龄', pinyin: 'niánlíng', meaning: 'age' },
      { word: '世纪', pinyin: 'shìjì', meaning: 'century' },
      { word: '年代', pinyin: 'niándài', meaning: 'era, decade' },
      { word: '未来', pinyin: 'wèilái', meaning: 'future' },
      { word: '过去', pinyin: 'guòqù', meaning: 'past' },
      { word: '永远', pinyin: 'yǒngyuǎn', meaning: 'forever, always' },
      // Space & Location
      { word: '方向', pinyin: 'fāngxiàng', meaning: 'direction' },
      { word: '东', pinyin: 'dōng', meaning: 'east' },
      { word: '南', pinyin: 'nán', meaning: 'south' },
      { word: '西', pinyin: 'xī', meaning: 'west' },
      { word: '北', pinyin: 'běi', meaning: 'north' },
      { word: '旁边', pinyin: 'pángbiān', meaning: 'beside, next to' },
      { word: '中间', pinyin: 'zhōngjiān', meaning: 'middle, between' },
      // Actions (advanced)
      { word: '欣赏', pinyin: 'xīnshǎng', meaning: 'to appreciate, to enjoy' },
      { word: '选择', pinyin: 'xuǎnzé', meaning: 'to choose, to select' },
      { word: '继续', pinyin: 'jìxù', meaning: 'to continue' },
      { word: '完成', pinyin: 'wánchéng', meaning: 'to complete, to finish' },
      { word: '表示', pinyin: 'biǎoshì', meaning: 'to express, to show' },
      { word: '认为', pinyin: 'rènwéi', meaning: 'to think, to consider' },
      { word: '建议', pinyin: 'jiànyì', meaning: 'to suggest, suggestion' },
      { word: '讨论', pinyin: 'tǎolùn', meaning: 'to discuss' },
      { word: '解决', pinyin: 'jiějué', meaning: 'to solve, to resolve' },
      // Descriptions (advanced)
      { word: '著名', pinyin: 'zhùmíng', meaning: 'famous, renowned' },
      { word: '优秀', pinyin: 'yōuxiù', meaning: 'outstanding, excellent' },
      { word: '重要', pinyin: 'zhòngyào', meaning: 'important' },
      { word: '必要', pinyin: 'bìyào', meaning: 'necessary' },
      { word: '可能', pinyin: 'kěnéng', meaning: 'possible, maybe' },
      { word: '安全', pinyin: 'ānquán', meaning: 'safe, safety' },
      { word: '危险', pinyin: 'wēixiǎn', meaning: 'dangerous' },
      { word: '普通', pinyin: 'pǔtōng', meaning: 'ordinary, common' },
      { word: '简单', pinyin: 'jiǎndān', meaning: 'simple' },
      { word: '复杂', pinyin: 'fùzá', meaning: 'complicated' },
      { word: '完全', pinyin: 'wánquán', meaning: 'completely, totally' },
      { word: '全部', pinyin: 'quánbù', meaning: 'all, entire' },
      // Comparison & Degree
      { word: '比较', pinyin: 'bǐjiào', meaning: 'to compare, relatively' },
      { word: '更加', pinyin: 'gèngjiā', meaning: 'even more' },
      { word: '十分', pinyin: 'shífēn', meaning: 'very, extremely' },
      { word: '相当', pinyin: 'xiāngdāng', meaning: 'quite, fairly' },
      { word: '几乎', pinyin: 'jīhū', meaning: 'almost, nearly' },
      // Connecting & Logic
      { word: '虽然', pinyin: 'suīrán', meaning: 'although' },
      { word: '如果', pinyin: 'rúguǒ', meaning: 'if' },
      { word: '只要', pinyin: 'zhǐyào', meaning: 'as long as' },
      { word: '不管', pinyin: 'bùguǎn', meaning: 'no matter, regardless' },
      { word: '除了', pinyin: 'chúle', meaning: 'except, besides' },
      { word: '甚至', pinyin: 'shènzhì', meaning: 'even, so much so that' },
      // Education & Learning
      { word: '理解', pinyin: 'lǐjiě', meaning: 'to understand, to comprehend' },
      { word: '复习', pinyin: 'fùxí', meaning: 'to review, to revise' },
      { word: '练习', pinyin: 'liànxí', meaning: 'to practice, exercise' },
      { word: '考试', pinyin: 'kǎoshì', meaning: 'exam, test' },
      { word: '成绩', pinyin: 'chéngjì', meaning: 'grade, score' },
      { word: '进步', pinyin: 'jìnbù', meaning: 'progress, to improve' },
      // Countries & Languages
      { word: '美国', pinyin: 'měiguó', meaning: 'America, USA' },
      { word: '英国', pinyin: 'yīngguó', meaning: 'United Kingdom' },
      { word: '法国', pinyin: 'fǎguó', meaning: 'France' },
      { word: '日本', pinyin: 'rìběn', meaning: 'Japan' },
      { word: '语言', pinyin: 'yǔyán', meaning: 'language' },
      // Competition & Achievement
      { word: '比赛', pinyin: 'bǐsài', meaning: 'competition, match' },
      { word: '冠军', pinyin: 'guànjūn', meaning: 'champion' },
      { word: '奖牌', pinyin: 'jiǎngpái', meaning: 'medal' },
      { word: '梦想', pinyin: 'mèngxiǎng', meaning: 'dream' },
      // Nature Phenomena
      { word: '地震', pinyin: 'dìzhèn', meaning: 'earthquake' },
      { word: '洪水', pinyin: 'hóngshuǐ', meaning: 'flood' },
      { word: '火山', pinyin: 'huǒshān', meaning: 'volcano' },
      { word: '瀑布', pinyin: 'pùbù', meaning: 'waterfall' },
      // Abstract Actions
      { word: '产生', pinyin: 'chǎnshēng', meaning: 'to produce, to generate' },
      { word: '发展', pinyin: 'fāzhǎn', meaning: 'to develop, development' },
      { word: '变化', pinyin: 'biànhuà', meaning: 'to change, change' },
      { word: '影响', pinyin: 'yǐngxiǎng', meaning: 'to influence, influence' },
      { word: '代表', pinyin: 'dàibiǎo', meaning: 'to represent, representative' },
      { word: '关系', pinyin: 'guānxi', meaning: 'relationship, connection' },
      { word: '差别', pinyin: 'chābié', meaning: 'difference' },
      { word: '优点', pinyin: 'yōudiǎn', meaning: 'strength, advantage' },
      { word: '缺点', pinyin: 'quēdiǎn', meaning: 'weakness, drawback' },
    ],
  },
]

export function getWordBook(levelId: number): WordBook | undefined {
  return WORD_BOOKS.find((b) => b.id === levelId)
}
